// src/lib/components/PlayerStatsRow.svelte
<script lang="ts">
  import type { PlayerStats } from '$app';
  import PlayerStatsCell from './PlayerStatsCell.svelte';

  export let player: PlayerStats;
  export let gamesCount: number|undefined;
</script>

<tr>
  <PlayerStatsCell>{player.position}</PlayerStatsCell>
  <PlayerStatsCell><a href={`/player/${player.uuid}`} class="underline">{player.name}</a></PlayerStatsCell>
  <PlayerStatsCell>{player.pointsRatio.toFixed(2)} %</PlayerStatsCell>
  <PlayerStatsCell>{player.wins}</PlayerStatsCell>
  <PlayerStatsCell>{player.games} ({gamesCount ? (player.games / gamesCount * 100).toFixed(2) : 0} %)</PlayerStatsCell>
  <PlayerStatsCell>{(player.wins / player.games).toFixed(2)} %</PlayerStatsCell>
</tr>

// src/components/player-stats-table/player-stats-row.tsx
import {Link} from 'react-router-dom';

import {PlayerStats} from '../../api/types';

import PlayerStatsCell from './player-stats-cell';

interface PlayerStatsRowProps {
  player: PlayerStats;
  gamesCount?: number;
}

const PlayerStatsRow = ({player, gamesCount}: PlayerStatsRowProps) => {
  const calculateGamesRatio = (): string => (
    gamesCount ? (player.games / gamesCount * 100).toFixed(2) : '0'
  );

  const calculateWinRatio = (): string => (player.wins / player.games * 100).toFixed(2);

  return (
    <tr>
      <PlayerStatsCell>{player.position}</PlayerStatsCell>
      <PlayerStatsCell><Link to={`/player/${player.uuid}`} className="underline">{player.name}</Link></PlayerStatsCell>
      <PlayerStatsCell>{player.pointsRatio.toFixed(2)}</PlayerStatsCell>
      <PlayerStatsCell>{player.wins}</PlayerStatsCell>
      <PlayerStatsCell>{player.games} ({calculateGamesRatio()} %)</PlayerStatsCell>
      <PlayerStatsCell>{calculateWinRatio()} %</PlayerStatsCell>
    </tr>
  );
};

export default PlayerStatsRow;
