// src/lib/components/PlayerStatsTable.svelte
<script lang="ts">
  import type { PlayerStats } from '$app';
  import PlayerStatsRow from './PlayerStatsRow.svelte';
  import PlayerStatsTableHeader from './PlayerStatsTableHeader.svelte';
  import SortablePlayerStatsTableHeader from './SortablePlayerStatsTableHeader.svelte';

  export let playerStats: PlayerStats[];
  export let gamesCount: number|undefined;
  export let sort: string = 'pointsRatio';
</script>

<table class="mx-auto text-xs md:text-base table-fixed">
  <thead>
  <tr>
    <PlayerStatsTableHeader>Pos ({playerStats.length})</PlayerStatsTableHeader>
    <PlayerStatsTableHeader>Player</PlayerStatsTableHeader>
    <SortablePlayerStatsTableHeader bind:sort={sort} sortName={'pointsRatio'}>Points</SortablePlayerStatsTableHeader>
    <SortablePlayerStatsTableHeader bind:sort={sort} sortName={'wins'}>Wins</SortablePlayerStatsTableHeader>
    <SortablePlayerStatsTableHeader bind:sort={sort} sortName={'games'}>Games ({gamesCount})</SortablePlayerStatsTableHeader>
    <SortablePlayerStatsTableHeader bind:sort={sort} sortName={'winRatio'}>Win Ratio</SortablePlayerStatsTableHeader>
  </tr>
  </thead>
  <tbody>
    {#each playerStats as player}
      <PlayerStatsRow player={player} gamesCount={gamesCount} />
    {/each}
  </tbody>
</table>

// src/components/player-stats-table/player-stats-table.tsx
import {PlayerStats} from '../../api/types';

import PlayerStatsTableHeader from './player-stats-table-header';
import SortablePlayerStatsTableHeader from './sortable-player-stats-table-header';
import PlayerStatsRow from './player-stats-row';

interface PlayerStatsTableProps {
  playerStats: PlayerStats[]|undefined;
  gamesCount: number|undefined;
  sort: string;
  sortHandler: (sortName: string) => void;
}

const PlayerStatsTable = ({playerStats, gamesCount, sort, sortHandler}: PlayerStatsTableProps) => {
  if (!playerStats) {
    return null;
  }

  return (
    <table className="mx-auto text-xs md:text-base table-fixed">
      <thead>
      <tr>
        <PlayerStatsTableHeader>Pos ({playerStats.length})</PlayerStatsTableHeader>
        <PlayerStatsTableHeader>Player</PlayerStatsTableHeader>
        <SortablePlayerStatsTableHeader selectedSort={sort} sort="pointsRatio" sortHandler={sortHandler}>Points</SortablePlayerStatsTableHeader>
        <SortablePlayerStatsTableHeader selectedSort={sort} sort="wins" sortHandler={sortHandler}>Wins</SortablePlayerStatsTableHeader>
        <SortablePlayerStatsTableHeader selectedSort={sort} sort="games" sortHandler={sortHandler}>Games ({gamesCount})</SortablePlayerStatsTableHeader>
        <SortablePlayerStatsTableHeader selectedSort={sort} sort="winRatio" sortHandler={sortHandler}>Win Ratio</SortablePlayerStatsTableHeader>
      </tr>
      </thead>
      <tbody>
        { playerStats.map((player: PlayerStats) => <PlayerStatsRow player={player} gamesCount={gamesCount} />) }
      </tbody>
    </table>
  );
};

export default PlayerStatsTable;
