// src/components/favorite-team/favorite-team.tsx
import {useEffect, useState} from 'react';

import {PlayerStats} from '../../api/types';
import {getFavoriteTeam} from '../../api/players';

import PlayerStatsTable from '../player-stats-table/player-stats-table';
import {useLocation} from "react-router-dom";

interface FavoriteTeamProps {
  player: PlayerStats;
}

const FavoriteTeam = ({player}: FavoriteTeamProps) => {
  const [fellowPlayers, setFellowPlayers] = useState<PlayerStats[]>()
  const [sort, setSort] = useState('pointsRatio')

  const {search} = useLocation();
  const allFavorite = new URLSearchParams(search).get('allFavorite');

  useEffect(() => {
    if (player) {
      const fetchFellowPlayers = async () => {
        const {playerStats} = await getFavoriteTeam(player.uuid, sort);

        setFellowPlayers(allFavorite ? playerStats : playerStats.slice(0, 5));
      };

      fetchFellowPlayers();
    }
  }, [player, sort])

  return (
    <div className="my-5">
      <h3 className="text-left text-sm md:text-xl font-bold">Favorite Team</h3>

      <PlayerStatsTable playerStats={fellowPlayers} gamesCount={player.games} sort={sort} sortHandler={setSort} />
    </div>
  );
};

export default FavoriteTeam;

// src/lib/components/FavoriteTeam.svelte
<script lang="ts">
  import type { PlayerStats } from '$app';
  import PlayerStatsTable from './PlayerStatsTable.svelte';
  import { PUBLIC_FSKICK_API_ENDPOINT } from '$env/static/public';

  export let player: PlayerStats;

  let fellowPlayers: PlayerStats[] = [];
  let sort: string = 'pointsRatio';

  $: fetchFellowPlayers(player, sort);

  const fetchFellowPlayers = async (player: PlayerStats, sort: string) => {
    const fellowPlayersResponse = await fetch(`${PUBLIC_FSKICK_API_ENDPOINT}/api/players/${player.uuid}/team?sort=${sort}`);
    if (!fellowPlayersResponse.ok) {
      return;
    }

    fellowPlayers = (await fellowPlayersResponse.json()).playerStats.slice(0, 5);
  };
</script>

<div class="my-5">
  <h3 class="text-left text-sm md:text-xl font-bold">Favorite Team</h3>

  <PlayerStatsTable playerStats={fellowPlayers} gamesCount={player?.games} bind:sort={sort} />
</div>
